config/routes.rb
Rails.application.routes.draw do

  post 'import_mark' => 'marks#import'
  get 'generate_marksheet' => 'marks#generate_marksheet'
  get 'genpdf' => 'marks#genpdf'
  get 'search_student' => 'marks#search'
  get 'students/search'
  resources :students
  resources :marks

  get 'courses/search'
  resources :courses
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'students#index'

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student_id, :internal, :external, presence: true
  validates :internal, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 20}
  validates :external, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 60} 

  def self.import(file, course_id, department_id)
    # xlsx =  Roo::Spreadsheet.open(file.path)
    begin
      # excel_file = file.original_filename =~ /.*\.xlsx$/i ? Roo::Excelx.new(file.path) : Roo::Excel.new(file.path)
      course_association = CourseAssociation.where(course_id: course_id, department_id: department_id).take 
      return 'no association' if course_association.nil?
      # debugger
      excel_file = Roo::Excelx.new(file.path) 

      header = excel_file.row(1).slice(0,3)
      header.map! do |word|
        word.strip.downcase
      end
      
      faulty_rows = Array.new
      all_grade_point_info = GradePoint.all.to_a
      (2..excel_file.last_row).each do |key, val|

        row = Hash[[header, excel_file.row(key).slice(0,3)].transpose]
     
        if row[header[1]].is_a? Numeric and row[header[2]].is_a? Numeric then
          student = Student.find_by regno: row[header[0]].to_i
          if student.nil?
            faulty_rows.push(key)
            next
          end
             
          course = Course.find(course_id)
          mark = Mark.where(course_id: course_id, student_id: student.id).take || new
          mark.internal = row[header[1]].to_i
          mark.external = row[header[2]].to_i
          mark.total = mark.internal + mark.external

          case 
          when mark.total >= 70
            mark.grade = 'O'

          when mark.total < 70 && mark.total >= 60 
            mark.grade = 'A'

          when mark.total < 60 && mark.total >=55
            mark.grade = 'B'

          when mark.total < 55 && mark.total >= 50
            row.grade = 'C'

          when mark.total < 50 && mark.total >= 45
            mark.grade = 'D'

          when mark.total < 45 && mark.total >=40
            mark.grade = 'E'

          when mark.total < 40 && mark.total >=0
            mark.grade = 'F'
          else 
            faulty_rows.push(key)
          end		
    
          grade_point = {}
          all_grade_point_info.each do | row |
            grade_point[row.grade.to_s] = row[:point]
          end

          mark.credit_point = course_association.credit_hour * grade_point[mark.grade] 
          mark.student = student
          mark.course = course
          faulty_rows.push(key) unless mark.save
        else
          faulty_rows.push(key)
        end
      end  

    rescue Exception => error
      faulty_rows.push(error)
    end 

    return faulty_rows

  end

end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  def edit
  end

  def index

  end

  def new
  end

  def show
  end

  def search
    @students = Student.where("regno like ?", "%#{params[:regno]}%")
    render 'index'
  end

  def import
    # debugger
    #if params[:file].original_filename =~ /.*\.xls|(xs)$/i  then
    # debugger
    flash_msg_elements = Array.new

    if params[:course][:id].blank?
      flash_msg_elements.push('Course')
    end
    if params[:department][:id].blank?
      flash_msg_elements.push('Department')
    end

    if flash_msg_elements.empty? then
      if params[:file].nil?
        flash_msg_elements.push('file')
      elsif params[:file].original_filename =~ /.*\.xlsx$/i  then
        #process the imported file file

        import_state = Mark.import(params[:file], params[:course][:id], params[:department][:id])
        if  import_state == false then
          flash[:error] = "File is not in the proper format"
        elsif import_state == 'no association'
          flash[:error] = "The selected department does not offer the selected course"
        elsif import_state.empty?
          flash[:success] = "All records have been inserted/updated successfully"
        else
          flash[:warning] = "There was an error in the following rows: " + import_state.join(", ")
        end

      else
        flash.now[:error] = "File type is not supported"
      end
    else
      flash.now[:error] = "Please ensure you select the following: " + flash_msg_elements.join(", ")
    end
    redirect_to action: :index
  end

  def generate_marksheet

  end

  def genpdf
    respond_to do |format|
      format.html
      format.pdf do 
        pdf = MarksheetPdf.new
        send_data pdf.render, filename: "test_file",
          type: "application/pdf",
          disposition: "inline"

        #  send_data pdf.render
      end
    end
  end
end

app/helpers/mark_helper.rb
module MarkHelper
end

app/views/marks/edit.html.erb
<h1>Mark#edit</h1>
<p>Find me in app/views/mark/edit.html.erb</p>

app/views/marks/generate_marksheet.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Search</h3>
  </div><!-- /.box-header -->
  <!-- form start -->
  <!-- <form class="form-horizontal"> -->


  <%= form_tag({controller: "marks", action: "search"}, method: 'get', class: "form-horizontal") do %>
    <div class="box-body">
    <div class="form-group">
      <label for="regno" class="col-sm-2 control-label">Department</label>
      <div class="col-sm-10">

        <%= collection_select(:course, :id, Department.all, :id, :name, options = {prompt: "Select Department"}, {class: "form-control col-sm-4"})  %> 
      </div>
    </div>

  </div><!-- /.box-body -->
  <div class="box-footer">
    <button type="submit" class="btn btn-default pull-right">Cancel</button>
    <%= submit_tag "Generate Result", {class: "btn btn-success pull-right"} %>
  </div><!-- /.box-footer -->
<% end %>
  <!-- </form> -->
</div><!-- /.box -->  

<%= link_to "Download PDF", genpdf_path(@user, format: "pdf"), class: "btn btn-success", target: "_blank"%>

app/views/marks/import.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <h3 class="box-title">Search</h3>
  </div><!-- /.box-header -->
  <!-- form start -->
  <!-- <form class="form-horizontal"> -->


  <%= form_tag({controller: "marks", action: "search"}, method: 'get', class: "form-horizontal") do %>
    <div class="box-body">
    <div class="form-group">
      <label for="regno" class="col-sm-2 control-label">Student Reg No</label>
      <div class="col-sm-10">
        <%= text_field_tag :regno, nil, { class: "form-control",placeholder: "reg no"}  %>

      </div>
    </div>

  </div><!-- /.box-body -->
  <div class="box-footer">
    <button type="submit" class="btn btn-default pull-right">Cancel</button>
    <%= submit_tag "Search", {class: "btn btn-success pull-right"} %>
  </div><!-- /.box-footer -->
<% end %>
  <!-- </form> -->
</div><!-- /.box -->  

<% unless @students.nil?  %>
  <ul class="list-group" >
  <% @students.each do |student| %>
    <li class="list-group-item"> <%= link_to student.regno.to_s + " " + student.first_name + " " + student.last_name, "#" %></li> 
<% end %>
</ul>

<% end  %>


<div class="box box-default">
  <div class="box-header with-border">
    <i class="fa fa-bullhorn"></i>
    <h3 class="box-title">IMPORTANT</h3>
  </div><!-- /.box-header -->
  <div class="box-body">
    <div class="callout callout-warning">
      <h4>Please ensure that you follow the format specified below:</h4>
      <ul>
        <li><p>There can be only 3 columns: Regno, Internal and External. Any column beyong the first 3 will be ignored</p></li>
        <li><p>Only ".xlsx" format is supported</p></li>
        <li><p>You must select the course and department before uploading the file</p></li>
        <li><p>A student must be already registered</p></li>

      </ul>
    </div>
    <!-- Form to upload file -->
    <%= form_tag(import_mark_path,{ multipart: true, class: "form-horizontal"} ) do  %>
      <div class = "form-group" >
      <label for="course_id" class="col-sm-2 control-label">Course</label>
      <div class="col-sm-10">
        <%= collection_select(:course, :id, Course.all, :id, :name, options = {prompt: "Select Course"}, {class: "form-control col-sm-4"})  %> 
      </div>
    </div>

    <div class = "form-group" >
      <label for="course_id" class="col-sm-2 control-label">Department</label>
      <div class="col-sm-10">
        <%= collection_select(:department, :id, Department.all, :id, :name, options = {prompt: "Select Department"}, {class: "form-control col-sm-4"})  %> 
      </div>
    </div>

    <div class="form-group">
      <label for="regno" class="col-sm-2 control-label">Excel File</label>
      <div class="col-sm-10">
        <%=	file_field_tag :file, accept: 'text/xlsx'  %>
      </div>
    </div>
    <%= submit_tag "Upload File", class: "btn btn-success pull-right" %>

  <% end  %>

  </div><!-- /.box-body -->
</div><!-- /.box -->

app/views/marks/index.html.erb
<div class="box box-success">
  <div class="box-header with-border">
    <i class="fa fa-bullhorn"></i>
    <h3 class="box-title">IMPORTANT</h3>
  </div><!-- /.box-header -->
  <div class="box-body">
    <div class="callout callout-warning">
      <h4>Please ensure that you follow the format specified below:</h4>
      <ul>
        <li><p>There can be only 3 columns: Regno, Internal and External. Any column beyond the first 3 will be ignored</p></li>
        <li><p>Only ".xlsx" format is supported</p></li>
        <li><p>You must select the course and department before uploading the file</p></li>
        <li><p>A student must be already registered</p></li>

      </ul>
    </div>
    <!-- Form to upload file -->
    <%= form_tag(import_mark_path,{ multipart: true, class: "form-horizontal"} ) do  %>
      <div class = "form-group" >
      <label for="course_id" class="col-sm-2 control-label">Course</label>
      <div class="col-sm-10">
        <%= collection_select(:course, :id, Course.all, :id, :name, options = {prompt: "Select Course"}, {class: "form-control col-sm-4"})  %> 
      </div>
    </div>

    <div class = "form-group" >
      <label for="course_id" class="col-sm-2 control-label">Department</label>
      <div class="col-sm-10">
        <%= collection_select(:department, :id, Department.all, :id, :name, options = {prompt: "Select Department"}, {class: "form-control col-sm-4"})  %> 
      </div>
    </div>

    <div class="form-group">
      <label for="regno" class="col-sm-2 control-label">Excel File</label>
      <div class="col-sm-10">
        <%=	file_field_tag :file, accept: 'text/xlsx'  %>
      </div>
    </div>
    <%= submit_tag "Upload File", class: "btn btn-success pull-right" %>

  <% end  %>

  </div><!-- /.box-body -->
</div><!-- /.box -->

app/views/marks/new.html.erb
<h1>Mark#new</h1>
<p>Find me in app/views/mark/new.html.erb</p>

app/views/marks/show.html.erb
<h1>Mark#show</h1>
<p>Find me in app/views/mark/show.html.erb</p>